### PR TITLE
Added polish translations

### PR DESCRIPTION
**Pull request by Blayung**
I've added all the polish translations. Also, all the advancements are unlocalized, so somebody could fix that maybe. And, as a Pole, I almost got a heart attack after I have seen this shit:

There's no way anyone would conjugate this noun like that. But I've deleted all my Ł's from the translations anyways. Gotta be correct.

### CODE REVIEW

**Comment by Mrbysco** [comment]
I'm aware of the advancements being unlocalized and plan on fixing that in the future by datagenning them.
Would you be interested in receiving the translator reward if so please provide your ingame name? (The reward will display enchantment table particles around a player statue with your username) (Example)
translator_reward

**Comment by Blayung** [comment]
Oh, I don't think that I'll be planning on using your mod, but sure. `_Blay_` is my current in-game username.

**Comment by Mrbysco** [comment]
I've since datagenned the advancements if you're still interested in translating those. I've added the missing entries to the `pl_pl.json`

**Comment by Blayung** [comment]
Well, I've translated this mod just for the modtoberfest, but once I have some free time on my hands I'll be able to translate these advancments too. 😀

**Comment by Mrbysco** [comment]
👍

**Pull request merged**
