### PR TITLE
Create nl_nl.json

### PR DESCRIPTION
**Pull request by ferriarnus**
Add Dutch lang files. Still not a 100% happy with it, as S.T.A.T.U.E is a hard one (and I need to spell-check it again).

### CODE REVIEW

**Comment by Mrbysco** [comment]
As of 3 days ago advancements have lang keys 😓

**Comment by ferriarnus** [comment]
Oh didn't see that, _guess I'll have to add these then_.

**Comment by Mrbysco** [comment]
I honestly don't mind, only do it if you want to else I'll just add the default English values so it won't show unlocalized keys :P This pr is already huge for us :)
translator_reward

Btw if you want the translator reward I'll need your mc username so I can add you to the reward list

**Comment by ferriarnus** [comment]
Now all keys should be in, but I'm gonna try and do another spellcheck pass. My mc name is `Ferri_Arnus` (chocking I know).

**Comment by Mrbysco** [comment]
Looks good so far :)

**Pull request merged**
